# Generated by Django 6.0.5 on 2026-05-24 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('discount_percent', models.FloatField(default=0.0)),
                ('trial_days', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.IntegerField(default=1)),
                ('uses_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(choices=[('TRIAL', 'Trial (فترة تجريبية)'), ('MONTHLY', 'Monthly (شهري)'), ('YEARLY', 'Yearly (سنوي)')], default='MONTHLY', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active (نشط)'), ('EXPIRED', 'Expired (منتهي)'), ('SUSPENDED', 'Suspended (معطل)')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True)),
                ('coupon_used', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licensing.licensekey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
