# Generated by Django 6.0.5 on 2026-05-26 19:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnclassifiedSMSReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('raw_sms', models.TextField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True)),
                ('license_key', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
