# Generated by Django 6.0.5 on 2026-06-15 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_wallet', models.CharField(default='01000000000', max_length=20, verbose_name='محفظة المدير المستلمة')),
                ('gateway_api_key', models.CharField(default='default_key_123456', max_length=100, verbose_name='مفتاح الـ API المشترك للبوابة')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.CreateModel(
            name='UnmatchedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_sms_body', models.TextField()),
                ('parsed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parsed_sender', models.CharField(max_length=20)),
                ('parsed_transaction_id', models.CharField(max_length=100, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='sender_wallet',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='license_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licensing.licensekey'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (معلقة)'), ('SUCCESS', 'Success (ناجحة)'), ('FAILED', 'Failed (فشلت)')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
