# Generated by Django 6.0.5 on 2026-06-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0004_siteconfiguration_unmatchedtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
