# Generated by Django 6.0.5 on 2026-06-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0006_userprofile_email_verified_userprofile_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='infobip_api_key',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Infobip API Key'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='infobip_base_url',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Infobip Base URL'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='infobip_from_email',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Infobip From Email'),
        ),
    ]
