# Generated by Django 6.0.5 on 2026-06-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0007_siteconfiguration_infobip_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='resend_api_key',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Resend API Key'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='resend_from_email',
            field=models.CharField(blank=True, default='onboarding@resend.dev', max_length=256, verbose_name='Resend From Email'),
        ),
    ]
