# Generated by Django 6.0.5 on 2026-06-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0008_siteconfiguration_resend_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='whatsapp_enabled',
            field=models.BooleanField(default=True, verbose_name='تفعيل إشعارات واتسآب'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='whatsapp_from_number',
            field=models.CharField(blank=True, default='447860088970', max_length=50, verbose_name='رقم واتسآب المرسل'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='whatsapp_template_language',
            field=models.CharField(default='en', max_length=10, verbose_name='لغة القوالب'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='whatsapp_template_otp',
            field=models.CharField(blank=True, default='test_whatsapp_template_en', max_length=100, verbose_name='اسم قالب الـ OTP'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='whatsapp_template_payment',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='اسم قالب تأكيد الدفع'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='whatsapp_template_welcome',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='اسم قالب الترحيب والتفعيل'),
        ),
    ]
