# Generated by Django 6.0.3 on 2026-06-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0009_siteconfiguration_whatsapp_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_id', models.CharField(max_length=100, unique=True, verbose_name='معرف النمط')),
                ('type', models.CharField(max_length=50, verbose_name='نوع العملية')),
                ('regex_pattern', models.TextField(verbose_name='تعبير Regex')),
                ('groups_json', models.TextField(default='{}', verbose_name='مجموعات التقاط Regex (JSON)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نمط تحليل الرسائل',
                'verbose_name_plural': 'أنماط تحليل الرسائل',
            },
        ),
    ]
