# Generated by Django 6.0.3 on 2026-06-26 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0010_smspattern'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantTransaction',
            fields=[
                ('transaction_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='معرف العملية الفريد')),
                ('type', models.CharField(max_length=50, verbose_name='نوع العملية')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الرصيد بعد العملية')),
                ('counterpart', models.CharField(blank=True, default='', max_length=100, verbose_name='الطرف الآخر')),
                ('raw_sms', models.TextField(verbose_name='الرسالة الخام')),
                ('parsed_at', models.DateTimeField(verbose_name='وقت التحليل')),
                ('sms_timestamp', models.DateTimeField(verbose_name='وقت الرسالة')),
                ('confidence', models.FloatField(default=1.0, verbose_name='الموثوقية')),
                ('wallet_id', models.CharField(blank=True, default='', max_length=50, verbose_name='معرف المحفظة')),
                ('profit_status', models.CharField(default='UNSET', max_length=50, verbose_name='حالة الربح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الاستلام على السيرفر')),
                ('license_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licensing.licensekey', verbose_name='مفتاح الترخيص')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_transactions', to=settings.AUTH_USER_MODEL, verbose_name='التاجر/المحل')),
            ],
            options={
                'verbose_name': 'عملية التاجر',
                'verbose_name_plural': 'عمليات التجار',
                'ordering': ['-sms_timestamp'],
            },
        ),
    ]
