# Generated by Django 6.0.5 on 2026-06-26 08:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0011_merchanttransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEPOSIT', 'Deposit (إيداع نقدية)'), ('WITHDRAWAL', 'Withdrawal (سحب نقدية)')], max_length=20, verbose_name='نوع الحركة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف/البيان')),
                ('source_tx_id', models.CharField(blank=True, default='', max_length=100, verbose_name='رمز العملية المرتبطة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الحركة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_ledger_records', to=settings.AUTH_USER_MODEL, verbose_name='التاجر')),
            ],
            options={
                'verbose_name': 'حركة الخزينة',
                'verbose_name_plural': 'حركات الخزينة',
                'ordering': ['-created_at'],
            },
        ),
    ]
